import type { Metadata } from "next";
import "./globals.css";
import { Providers } from '../store/Providers';
import { Header } from '../components';

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
	return (
		<html lang="es">
			<body suppressHydrationWarning={ true }>
				<main className='pokemon-app'>
					<Header/>
					<section className="pokemon-app__content">
						<Providers>
							{ children }
						</Providers>
					</section>
				</main>
			</body>
		</html>
	);
}
