import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '../components'
import { ThemeProvider } from '@mui/material/styles'
import darkTheme from './theme'

const inter = Inter({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="es">
			<body className={ inter.className } suppressHydrationWarning={ true }>
				<ThemeProvider theme={ darkTheme }>
					<main className='pokemon-app'>
						<Header/>
						<section className="pokemon-app__content">
							{ children }
						</section>
					</main>
				</ThemeProvider>
			</body>
		</html>
	)
}
